language: R
warnings_are_errors: true
cache: packages
dist: xenial
r_binary_packages:
  - rgl
os:
- linux
- osx
r_check_args: "--as-cran --install-args=--build"
notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      sudo apt-get -y install bc binutils libgomp1 perl psmisc sudo tar tcsh unzip uuid-dev vim-common libjpeg62-dev || true ;
      travis_wait 20 wget --quiet -O freesurfer.tar.gz https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz ;
      travis_wait 20 sudo tar -C /usr/local -xzf freesurfer.tar.gz ;
      export FREESURFER_HOME=/usr/local/freesurfer; source $FREESURFER_HOME/SetUpFreeSurfer.sh ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      travis_wait 20 wget --quiet -O freesurfer.dmg https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Darwin-OSX-stable-pub-v6.0.0.dmg ;
      sudo hdiutil attach freesurfer.dmg ;
      sudo installer -package /Volumes/freesurfer-Darwin-full/freesurfer-Darwin-full.pkg -target / ;
      sudo hdiutil detach /Volumes/freesurfer-Darwin-full ;
      export FREESURFER_HOME=/Applications/freesurfer; source $FREESURFER_HOME/SetUpFreeSurfer.sh ;
    fi
  - Rscript -e "system(\"export FREESURFER_HOME=${FREESURFER_HOME}; source ${FREESURFER_HOME}/FreeSurferEnv.sh\")" || true ;
  - Rscript -e "system(\"export FREESURFER_HOME=${FREESURFER_HOME}; . ${FREESURFER_HOME}/FreeSurferEnv.sh\")" || true ;


deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: YJBgiYTBtrnsuuWpemDxB2HmtTWmHPOstIVyXRUMua/h422C+2Nkud7WhEOo9v/LXg+TVDEpGAvsFajEqHTf0qk+Hb1AfyxhkQTv3SGFAJd7F5Ifs7PxpA5V7itI/JLZl0aIsw6EKEKp3EVt0ACnEqkQbkanWA4L8xR5dk0dk6KK0YRL7BumLDwfJjurQKARvEXfeK+jMB2VYiE8j1w2eYYEfmyZxRObau7erb0IAhtYduWw+/pU6E2ty2LAQPtFMEptqSLSMsPaxJfAH+QV/jOjNjSKP5n7D8SwwlflkcCXa3fVE2vWcI5GaELC5im8G6W1X2UtWKBfThqeI1D1Hh01H+gSUcj4wpYq4AbEiP+R0/jwwQ5jghtKevD0/7E+ybTPw9otycTIHwC8uizat+XR3cCMqQeBOH/IxeMjL747bFk3/Rs9DMaRGZSzosGDxkpfmvd/rIYJTStsD2dlcakzOnM31l5dN+3cyxh6Kx2WETZbpQtlgp8m4wWKJs4KCUofXDytyYEhynObF3LaUglAovvJf1btizsSuFRzibvrAym9qDba9pUoAFuXhzMxMe6Zd5thdEkU3hhC4KJW0Yj6HcvnjNn9kJ+kD2MGJaM3Eq/+SS34rylIKIfsJ9AD7Q7ZSLVRnKDSADSSBKD8VNLvw7E7JVi/aSeNscITcOA=
  file_glob: true    
  file: freesurfer*.t*gz
  on:
    tags: true    
    repo: muschellij2/freesurfer


