# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: true
sudo: false
cache: packages

os:
  - linux
  - osx


r_check_args: --as-cran --install-args=--build


notifications:
  email:
    on_success: change
    on_failure: change
