language: R
warnings_are_errors: true
cache: packages
dist: xenial
r_binary_packages:
  - rgl
os:
- linux
- osx
r_check_args: "--as-cran --install-args=--build"
notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}
  - fsl_install ;
  - freesurer_install ;
  - Rscript -e 'install.packages("base64enc")' ;
  - export license_file=${FREESURFER_HOME}/license.txt;
  - sudo chown -R $(whoami) ${FREESURFER_HOME} ;
  - touch $license_file ;
  - Rscript -e "cat(rawToChar(base64enc::base64decode(\"${FREESURFER_LICENSE}\")), file = \"${license_file}\")" ;
  - export PATH=${PATH}:${FREESURFER_HOME}/bin:${FREESURFER_HOME}/mni/bin ;


deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: YJBgiYTBtrnsuuWpemDxB2HmtTWmHPOstIVyXRUMua/h422C+2Nkud7WhEOo9v/LXg+TVDEpGAvsFajEqHTf0qk+Hb1AfyxhkQTv3SGFAJd7F5Ifs7PxpA5V7itI/JLZl0aIsw6EKEKp3EVt0ACnEqkQbkanWA4L8xR5dk0dk6KK0YRL7BumLDwfJjurQKARvEXfeK+jMB2VYiE8j1w2eYYEfmyZxRObau7erb0IAhtYduWw+/pU6E2ty2LAQPtFMEptqSLSMsPaxJfAH+QV/jOjNjSKP5n7D8SwwlflkcCXa3fVE2vWcI5GaELC5im8G6W1X2UtWKBfThqeI1D1Hh01H+gSUcj4wpYq4AbEiP+R0/jwwQ5jghtKevD0/7E+ybTPw9otycTIHwC8uizat+XR3cCMqQeBOH/IxeMjL747bFk3/Rs9DMaRGZSzosGDxkpfmvd/rIYJTStsD2dlcakzOnM31l5dN+3cyxh6Kx2WETZbpQtlgp8m4wWKJs4KCUofXDytyYEhynObF3LaUglAovvJf1btizsSuFRzibvrAym9qDba9pUoAFuXhzMxMe6Zd5thdEkU3hhC4KJW0Yj6HcvnjNn9kJ+kD2MGJaM3Eq/+SS34rylIKIfsJ9AD7Q7ZSLVRnKDSADSSBKD8VNLvw7E7JVi/aSeNscITcOA=
  file_glob: true    
  file: freesurfer*.t*gz
  on:
    tags: true    
    repo: muschellij2/freesurfer


